### ISSUE TITLE
Error OBJECT_WAS_NOT_CREATED if a user is already in a friends list.

### ISSUE THREAD

**Issue by Blady-Com** [jrcarter/Chattanooga#1]
Hello Jeff,

If a user is already in a friends list then his connection provoque the following exception:
2017-07-02 10:55:26.18 : On_Connect_Submit: raised GNOGA.GUI.BASE.OBJECT_WAS_NOT_CREATED : gnoga-gui-base.adb:2214
Load address: 0x100000000
Call stack traceback locations:
0x100184237 0x1001846e0 0x10017c8eb 0x10015508e 0x100023018 0x10001e829 0x1000184d9 0x10001879d 0x100018580 0x10001e130 0x10001ea77 0x10001ddc0 0x100026088 0x10017dfdd 0x100181fa1 0x1000f7b5f 0x10024dbc5 0x7fff8e1ec99b 0x7fff8e1ec918
cmd$ atos.sh bin/chattanooga 0x100184237 0x1001846e0 0x10017c8eb 0x10015508e 0x100023018 0x10001e829 0x1000184d9 0x10001879d 0x100018580 0x10001e130 0x10001ea77 0x10001ddc0 0x100026088 0x10017dfdd 0x100181fa1 0x1000f7b5f 0x10024dbc5 0x7fff8e1ec99b 0x7fff8e1ec918
gnoga__gui__base__jquery (in chattanooga) + 189
gnoga__gui__base__jquery_execute (in chattanooga) + 180
gnoga__gui__base__execute (in chattanooga) + 383
gnoga__gui__element__form__add_option__2 (in chattanooga) + 1564
**chattanooga__ui__new_friend (in chattanooga) (chattanooga-ui.adb:72)**
chattanooga__db__controlT__add__check_one.13117 (in chattanooga) (chattanooga-db.adb:78)
chattanooga__db__user_maps__iterate__process_node.12446 (in chattanooga) (a-cohama.adb:713)
chattanooga__db__user_maps__iterate__local_iterate.12449 (in chattanooga) (a-chtgop.adb:452)
chattanooga__db__user_maps__iterateXn (in chattanooga) (a-cohama.adb:722)
chattanooga__db__control__addN (in chattanooga) (chattanooga-db.adb:88)
chattanooga__db__control__addP (in chattanooga) (chattanooga-db.adb:65)
chattanooga__db__add (in chattanooga) (chattanooga-db.adb:31)
chattanooga__ui__on_connect_submit (in chattanooga) (chattanooga-ui.adb:203)
gnoga__gui__base__fire_on_submit (in chattanooga) + 143
gnoga__gui__base__on_message (in chattanooga) + 809
gnoga__server__connection__dispatch_task_typeTB (in chattanooga) + 2255
system__tasking__stages__task_wrapper (in chattanooga) + 437
0x7fff8e1ec99b
0x7fff8e1ec918

In call to New_Friend, App_Data.List is not yet created.
I've found a workaround: in On_Connect_Submit I've just put DB.Add at the end, see attached patch.
Maybe not the most relevant.

[patch-chat_diff.txt](https://github.com/jrcarter/Chattanooga/files/1117724/patch-chat_diff.txt)

HTH, Pascal.

**Comment by jrcarter** [comment]
On 07/02/2017 12:19 PM, Blady-Com wrote:
>
> In call to New_Friend, App_Data.List is not yet created.
> I've found a workaround: in On_Connect_Submit I've just put DB.Add at the end,
> see attached patch.
> Maybe not the most relevant.
>
Interesting. Check out commit c1d52b72c56033c328c838b4726a2dd5a019bbf2.

-- 
Jeff Carter
"I blow my nose on you."
Monty Python & the Holy Grail
03


---
This email has been checked for viruses by AVG.
http://www.avg.com

**Comment by jrcarter** [comment]
Latest commit seems to correct this.
